[licenses]
version = 2
unused-allowed-license = "deny"
allow = [
    "Apache-2.0",
    "MIT",
    "CC0-1.0",
    "Unlicense",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "0BSD",
    "ISC",
    "BSL-1.0",
    "Zlib",
    "CDLA-Permissive-2.0",
    "Unicode-3.0",
]

[licenses.private]
ignore = true

# TODO We should be able to remove `ignore-sources` once we add `publish = false` to all the crates sourced from here.
ignore-sources = ["https://github.com/WalletConnect/utils-rs.git"]
